# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vasco Correia
subtitle: Passionate Learner
email: vasco.h.correia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Find all my projects in just one place!
url: https://VascoCorreia.github.io
github_username: VascoCorreia
minimal_mistakes_skin: neon # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
repository: VascoCorreia/VascoCorreia.github.io
logo: "/assets/images/MastheadLogo.png"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: Portugal

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Vasco Correia"
  avatar : "/assets/images/vasco.jpg"
  bio    : "Game programmer, with a degree in Games and Apps Development.  I have a big interest in Technology, Physics and astronomy!"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VascoCorreia"
    -  label: "LinkedIn"
       icon: "fab fa-linkedin"
       url: "https://www.linkedin.com/in/vasco-correia-6b6811208/"
    -  label: "Email"
       icon: "fas fa-envelope"
       url: "mailto:vasco.h.correia@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VascoCorreia"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/vasco-correia-6b6811208/"
    -  label: "Email"
       icon: "fas fa-envelope"
       url: "mailto:vasco.h.correia@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

lunr:
  search_within_pages: true